version: 2
jobs:
  build:
    docker:
      # In advanced project settings one can set private variables such as the docker username and password
      #- image: bakerb845/mkl-iscl-build
      #  auth:
      #     username: $DOCKER_USER
      #     password: $DOCKER_PASS
      - image: bakerb845/ubuntu-rtseis
    steps:
      - checkout
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Build the code
          command: |
            export CC=gcc-7
            export CXX=g++-7
            export IPP_DIR=/opt/intel/ipp
            export IPP_LIB_ROOT=${IPP_DIR}/lib/intel64
            export MKL_DIR=/opt/intel/mkl
            export MKL_LIB_ROOT=${MKL_DIR}/lib/intel64
            export BUILD_DIR=build
            export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${IPP_LIB_ROOT}
            if [ -d ${BUILD_DIR} ]; then
               echo "Removing build directory" ${BUILD_DIR}
               rm -rf ${BUILD_DIR}
            fi
            mkdir ${BUILD_DIR}
            cd ${BUILD_DIR}
            cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_COMPILER=g++-7 \
            -DCMAKE_CXX_FLAGS="-Wall -Wl,--no-as-needed" \
            -DMKL_INCLUDE_DIR="${MKL_DIR}/include" \
            -DMKL_LIBRARY="${MKL_LIB_ROOT}/libmkl_intel_lp64.so;${MKL_LIB_ROOT}/libmkl_sequential.so;${MKL_LIB_ROOT}/libmkl_core.so;${MKL_LIB_ROOT}/libmkl_avx2.so" \
            -Dpybind11_INCLUDE_DIR="/usr/local/include/pybind11"
            cd ..
      - run:
          name: Build
          command: |
            cd build
            make
      - run:
          name: Test the code
          command: |
            cd build
            ctest --verbose
      - run:
          name: Test intsall
          command: |
            cd build
            make install
